---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
    playbook: test-java8.yml
  - distro: debian9
    playbook: test-java10.yml

  - distro: debian8
    playbook: test-java8.yml
  - distro: debian8
    playbook: test-java10.yml

  - distro: ubuntu1804
    playbook: test-java10.yml

  - distro: ubuntu1604
    playbook: test-java8.yml
  - distro: ubuntu1604
    playbook: test-java10.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check java is installed
  - ${DOCKER} java -version

after_failure:
  - ${DOCKER} which java
  - ${DOCKER} service java status
  - ${DOCKER} java --version

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
